### ISSUE TITLE
GUI not showing in Jupyter Notebook

### ISSUE THREAD

**Issue by Camilo318** [digitronik/tutorial-tkinter#3]
Hey pal, I´ve following your tutorial and so far it's been really helpful, Great Job!
But when I try to do so in Jupyter Notebook nothing shows up.

![image](https://user-images.githubusercontent.com/46302289/77777323-6808ef80-701d-11ea-8e58-5f473a1156f8.png)

When I run the cell with the mainloop method, everything freezes. I gues it keeps looping waiting for the user to close the window, but such window never appears.

Hope you've got a piece of advised for this one.
Regards

**Comment by digitronik** [comment]
trackback will be helfull. I don't found any problem with code or Jupiter notebook
![Screenshot_2020-03-29_18-40-35](https://user-images.githubusercontent.com/11618054/77849950-f5e70500-71ec-11ea-98e9-0c8890954bd3.png)
